export const standard = [
  [
    "Delightful",
    "Amazing",
    "Reliable",
    "Friendly",
    "Wholesome",
    "Royal",
    "Gorgeous",
    "Fortunate",
    "Calm",
    "Distinct",
    "Hilarious",
    "Graceful",
    "Virtuous",
    "Adventurous",
    "Exceptional",
    "Crazy",
    "Cooked",
    "Instinctual",
    "Overpowered",
    "Robotic",
    "Peaceful",
    "Confident",
  ],
  [
    "Pineapple",
    "Tomato",
    "Grape",
    "Apple",
    "Pear",
    "Peach",
    "Blueberry",
    "Raisin",
    "Strawberry",
    "Orange",
    "Banana",
    "Raspberry",
    "Carrot",
    "Artichoke",
    "Spinach",
    "Potato",
    "Pickle",
    "Durian",
    "Mango",
    "Avocado",
    "Cherry",
    "Apricot",
  ],
  [
    "Pizza",
    "Juice",
    "Soup",
    "Meal",
    "Blend",
    "Essence",
    "Potion",
    "Elixir",
    "Stew",
    "Cake",
    "Ice Cream",
    "Dessert",
    "Milkshake",
    "Mash",
    "Pie",
    "Slices",
    "Sandwich",
    "Tortilla",
    "Soda",
    "Omelette",
  ],
];

export const halloween = [
  ["Spooky", "Scary", "Boo-tiful", "Spine-tingling", "Bone-chilling", "Fang-tastic", "Ghostly", "Haunted"],
  ["Pumpkin", "Apple", "Caramel"],
  ["Pie", "Bread", "Corn", "Cake", "Cookies", "Candy"],
];
