version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dani_server_utils
    env_file: .env
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: ["yarn", "dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      CONNECTION_URL: ${mongodb_connection_url}

volumes:
  mongo_data:
  node_modules:
