services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    environment:
      - CONNECTION_URL=${MONGODB_URL}
networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
